# Site settings
title: Practical Executive
email: me@joshuaschultz.com
description: How to take your small business to the next level through data driven insights and experience forged expertise.
baseurl: ""
url: ""
twitter_username: joshuamschultz
github_username:  joshuamschultz

# Build settings
markdown: kramdown
gems: [jekyll-paginate]

paginate: 3
paginate_path: "blog/page:num"
