# Site settings
title: Practical Executive
email: me@joshuaschultz.com
description: How to take your small business to the next level through data driven insights and experience forged expertise.
baseurl: ""
url: http://joshuaschultz.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems: [jekyll-paginate]

paginate: 3
paginate_path: "blog/page:num"